apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.dbServiceName }}
  labels:
    app: {{ .Values.dbServiceName }}
spec:
  ports:
  - port: 5432
    protocol: TCP
  selector:
    app: {{ .Values.dbName }}