# templates/postgresql-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-app-chart.fullname" . }}-postgresql
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: {{ .Chart.Name }}-postgresql
          image: postgres:12
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.postgresUser }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresql.postgresPassword }}
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.postgresDatabase }}
